CREATE OR REPLACE SYNONYM APP_TC.LOOKUP FOR DBO_MP.LOOKUP;
GRANT ALL ON DBO_MP.LOOKUP TO APP_TC;

CREATE OR REPLACE SYNONYM APP_TC.LOOKUP_TYPE FOR DBO_MP.LOOKUP_TYPE;
GRANT ALL ON DBO_MP.LOOKUP_TYPE TO APP_TC;

CREATE OR REPLACE SYNONYM APP_DP.LOOKUP FOR DBO_MP.LOOKUP;
GRANT ALL ON DBO_MP.LOOKUP TO APP_DP;

CREATE OR REPLACE SYNONYM APP_DP.LOOKUP_TYPE FOR DBO_MP.LOOKUP_TYPE;
GRANT ALL ON DBO_MP.LOOKUP_TYPE TO APP_DP;

CREATE OR REPLACE SYNONYM APP_MP.LOOKUP FOR DBO_MP.LOOKUP;
GRANT ALL ON DBO_MP.LOOKUP TO APP_MP;

CREATE OR REPLACE SYNONYM APP_MP.LOOKUP_TYPE FOR DBO_MP.LOOKUP_TYPE;
GRANT ALL ON DBO_MP.LOOKUP_TYPE TO APP_MP;

COMMIT;