TRUNCATE TABLE DBO_TC.SYS_PROP_RC;
COMMIT;

BEGIN
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Acquisitions','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Administration','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Animation','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Below-The-Line','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Bond Company','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Book','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Business','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Business Affairs','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Camera Package','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Casting','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Caterer','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Clearance','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Commercial','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Corporate','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Dance','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Development','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Dgtl Intrmd Fac','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Distribution','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Distributor','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Electric Package','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Executive Producers','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Exhibition','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Film','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Film Commissioner','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Film/TV','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Final Mix','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Finance','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Game Shows','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Grip Package','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Guild','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Insurance Carrier','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Legal','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Legal Affairs','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Licensing','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Literary','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Marketing','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Memberships','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Music','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Music/Record Company','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('New Media','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('News','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('On-Camera','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Owner','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Packaging','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Partner','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Payroll Company','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Personal Appearance','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Post Production','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Principal','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Print','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Producer','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Prom','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Publicity','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Release Print Lab','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sales','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Scoring','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sound Effects','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sports','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Stage','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Stunts','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Talent','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Technical','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Technology','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Television','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Theatrical','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Trade Association','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Trade Show','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Union','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('VFX Vendor','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Voice-Over','CONTACT_TYPE');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Youth','CONTACT_TYPE');
COMMIT;
END;
/

--CONTACT_TYPE
DECLARE
		V_SYS_PROP_EXIST VARCHAR2(5);
    V_SYS_PROP_ID NUMBER;
    V_SORT_ORDER NUMBER;
    ----------------------------
      CURSOR C1 IS SELECT * FROM DBO_TC.SYS_PROP_RC
		WHERE SYS_PROPERTY='CONTACT_TYPE';
    ------------------------------
		FUNCTION SYS_PROP_VALUE_FNC(P_SYS_PROP_VALUE IN VARCHAR2,P_SYS_PROP_NAME IN VARCHAR2)
    RETURN VARCHAR2
		AS
		V_SYS_PROP_EXIST VARCHAR2(1);
		BEGIN
		SELECT 'Y'
		INTO V_SYS_PROP_EXIST
		FROM DBO_TC.SYS_PROPERTY SP,
		DBO_TC.SYS_PROP_VALUE SPV
		WHERE 
		SP.SYS_PROP_ID=SPV.SYS_PROP_ID
		AND UPPER(SPV.PROP_VALUE)=TRIM(UPPER(P_SYS_PROP_VALUE))
		AND UPPER(SP.SYS_PROP_NAME)=TRIM(UPPER(P_SYS_PROP_NAME));
		RETURN V_SYS_PROP_EXIST;
		EXCEPTION
			WHEN OTHERS THEN
				V_SYS_PROP_EXIST:='N';
				RETURN V_SYS_PROP_EXIST;
		END SYS_PROP_VALUE_FNC;
		--===============================
		PROCEDURE  SYS_PROP_VALUE_INS(P_SYS_PROP_VALUE IN VARCHAR2,P_SYS_PROP_ID IN NUMBER,P_SORT_ORDER IN NUMBER)
		AS
		BEGIN
		INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) 
		VALUES (DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL,P_SYS_PROP_ID,P_SYS_PROP_VALUE,P_SYS_PROP_VALUE,P_SORT_ORDER);
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
		END SYS_PROP_VALUE_INS;
		--=============================================

    BEGIN
		--
		BEGIN
		  SELECT SP.SYS_PROP_ID,MAX(SORT_ORDER)
		  INTO V_SYS_PROP_ID,V_SORT_ORDER
		  from DBO_TC.SYS_PROPERTY SP
		, DBO_TC.SYS_PROP_VALUE SPN
		WHERE SYS_PROP_NAME='CONTACT_TYPE'
		AND SPN.SYS_PROP_ID=SP.SYS_PROP_ID
		GROUP BY SP.SYS_PROP_ID;
		  EXCEPTION
			WHEN OTHERS  THEN 
			  DBMS_OUTPUT.PUT_LINE('V_SYS_PROP_ID for does not exist CONTACT_TYPE');
		END;
		IF V_SYS_PROP_ID IS NOT NULL THEN 
		--
		FOR I IN C1 
		LOOP
			BEGIN
			V_SYS_PROP_EXIST:='N';
			V_SORT_ORDER:=V_SORT_ORDER+1;
			V_SYS_PROP_EXIST:=SYS_PROP_VALUE_FNC(I.SYS_PROP_VALUE,I.SYS_PROPERTY);
			IF V_SYS_PROP_EXIST='N' THEN 
				SYS_PROP_VALUE_INS(I.SYS_PROP_VALUE,V_SYS_PROP_ID,V_SORT_ORDER);
			END IF;
			END;
      END LOOP;
			--
		END IF;
		COMMIT;
	END;
	/
	