-- Insert in SYS_PROPERTY with accented characters type
Insert into DBO_TC.SYS_PROPERTY (SYS_PROP_ID,SYS_PROP_NAME) values (SEQ_SYS_PROP_ID.NEXTVAL,'ACCENTED_CHAR_A');
Insert into DBO_TC.SYS_PROPERTY (SYS_PROP_ID,SYS_PROP_NAME) values (SEQ_SYS_PROP_ID.NEXTVAL,'ACCENTED_CHAR_E');
Insert into DBO_TC.SYS_PROPERTY (SYS_PROP_ID,SYS_PROP_NAME) values (SEQ_SYS_PROP_ID.NEXTVAL,'ACCENTED_CHAR_I');
Insert into DBO_TC.SYS_PROPERTY (SYS_PROP_ID,SYS_PROP_NAME) values (SEQ_SYS_PROP_ID.NEXTVAL,'ACCENTED_CHAR_N');
Insert into DBO_TC.SYS_PROPERTY (SYS_PROP_ID,SYS_PROP_NAME) values (SEQ_SYS_PROP_ID.NEXTVAL,'ACCENTED_CHAR_O');
Insert into DBO_TC.SYS_PROPERTY (SYS_PROP_ID,SYS_PROP_NAME) values (SEQ_SYS_PROP_ID.NEXTVAL,'ACCENTED_CHAR_U');
Insert into DBO_TC.SYS_PROPERTY (SYS_PROP_ID,SYS_PROP_NAME) values (SEQ_SYS_PROP_ID.NEXTVAL,'ACCENTED_CHAR_Y');


-- Insert in SYS_PROP_VALUE with accented characters values for "A"
--Grave
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_A'),'à','Grave',1);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_A'),'À','Grave',2);
--Acute
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_A'),'á','Acute',3);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_A'),'Á','Acute',4);
--Circumflex
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_A'),'â','Circumflex',5);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_A'),'Â','Circumflex',6);
--Tilde
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_A'),'ã','Tilde',7);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_A'),'Ã','Tilde',8);
--Umlaut
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_A'),'ä','Umlaut',9);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_A'),'Ä','Umlaut',10);

-- Insert in SYS_PROP_VALUE with accented characters values for "E" -  è È é É ê Ê ë Ë
--Grave
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_E'),'è','Grave',1);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_E'),'È','Grave',2);
--Acute
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_E'),'é','Acute',3);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_E'),'É','Acute',4);
--Circumflex
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_E'),'ê','Circumflex',5);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_E'),'Ê','Circumflex',6);
--Umlaut
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_E'),'ë','Umlaut',7);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_E'),'Ë','Umlaut',8);

-- Insert in SYS_PROP_VALUE with accented characters values for "I" - ì Ì í Í î Î ï Ï
--Grave
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_I'),'ì','Grave',1);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_I'),'Ì','Grave',2);
--Acute
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_I'),'í','Acute',3);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_I'),'Í','Acute',4);
--Circumflex
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_I'),'î','Circumflex',5);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_I'),'Î','Circumflex',6);
--Umlaut
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_I'),'ï','Umlaut',7);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_I'),'Ï','Umlaut',8);

-- Insert in SYS_PROP_VALUE with accented characters values for "N" - ñ Ñ
--Tilde
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_N'),'ñ','Tilde',1);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_N'),'Ñ','Tilde',2);

-- Insert in SYS_PROP_VALUE with accented characters values for "O" - ò Ò ó Ó ô Ô õ Õ ö Ö
--Grave
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_O'),'ò','Grave',1);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_O'),'Ò','Grave',2);
--Acute
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_O'),'ó','Acute',3);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_O'),'Ó','Acute',4);
--Circumflex
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_O'),'ô','Circumflex',5);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_O'),'Ô','Circumflex',6);
--Tilde
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_O'),'õ','Tilde',7);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_O'),'Õ','Tilde',8);
--Umlaut
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_O'),'ö','Umlaut',9);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_O'),'Ö','Umlaut',10);

-- Insert in SYS_PROP_VALUE with accented characters values for "U" - ù Ù ú Ú û Û ü Ü
--Grave
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_U'),'ù','Grave',1);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_U'),'ù','Grave',2);
--Acute
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_U'),'ú','Acute',3);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_U'),'Ú','Acute',4);
--Circumflex
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_U'),'û','Circumflex',5);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_U'),'Û','Circumflex',6);
--Umlaut
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_U'),'ü','Umlaut',7);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_U'),'Ü','Umlaut',8);

-- Insert in SYS_PROP_VALUE with accented characters values for "Y" - ý Ý ÿ Ÿ
--Acute
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_Y'),'ý','Acute',1);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_Y'),'Ý','Acute',2);
--Umlaut
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_Y'),'ÿ','Umlaut',3);
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'ACCENTED_CHAR_Y'),'Ÿ','Umlaut',4);

Commit;