ALTER table DBO_TC.COMPANY ADD INCORPORATION_STATE NUMBER(11,0) NULL;
ALTER TABLE DBO_TC.COMPANY ADD CONSTRAINT FK_INCORPORATION_STATE FOREIGN KEY (INCORPORATION_STATE) REFERENCES DBO_TC.SYS_PROP_VALUE(PROP_ID);

ALTER table DBO_TC.COMPANY ADD INCORPORATION_COUNTRY NUMBER(11,0) NULL;
ALTER TABLE DBO_TC.COMPANY ADD CONSTRAINT FK_INCORPORATION_COUNTRY FOREIGN KEY (INCORPORATION_COUNTRY) REFERENCES DBO_TC.SYS_PROP_VALUE(PROP_ID);

COMMIT;
