CREATE TABLE DBO_TC.WORK_ELIGIBILITY
(
  ID								NUMBER(11,0)          NOT NULL,
  PARTY_ID							NUMBER(11,0)          NOT NULL,
  WORK_ELIG_TYPE_NAME_ID			NUMBER(11,0)          NOT NULL,
  COUNTRY							NUMBER(11,0),
  EXPIRY_DATE						DATE,
  STATUS							NUMBER(11,0),
  LAST_UPDATED_USER					VARCHAR2(50 BYTE)     NOT NULL,
  LAST_UPDATED_TS					TIMESTAMP(9) DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_WORK_ELIGIBILITY PRIMARY KEY (ID)

);

ALTER TABLE DBO_TC.WORK_ELIGIBILITY ADD CONSTRAINT FK_WORK_PARTY_ID FOREIGN KEY(PARTY_ID) REFERENCES DBO_TC.PARTY(PARTY_ID);
ALTER TABLE DBO_TC.WORK_ELIGIBILITY ADD CONSTRAINT FK_WORK_ELIG_TYPE_NAME_ID FOREIGN KEY(WORK_ELIG_TYPE_NAME_ID) REFERENCES DBO_TC.SYS_PROP_VALUE(PROP_ID);

--Sequence for ID
CREATE SEQUENCE DBO_TC.SEQ_WORK_ELIGIBILITY_ID  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

------------- Create synonyms
CREATE OR REPLACE SYNONYM APP_TC.SEQ_WORK_ELIGIBILITY_ID FOR DBO_TC.SEQ_WORK_ELIGIBILITY_ID;
grant all on DBO_TC.SEQ_WORK_ELIGIBILITY_ID to APP_TC;

CREATE OR REPLACE SYNONYM APP_MP.SEQ_WORK_ELIGIBILITY_ID FOR DBO_TC.SEQ_WORK_ELIGIBILITY_ID;
grant all on DBO_TC.SEQ_WORK_ELIGIBILITY_ID to APP_MP;

CREATE OR REPLACE SYNONYM APP_DP.SEQ_WORK_ELIGIBILITY_ID FOR DBO_TC.SEQ_WORK_ELIGIBILITY_ID;
grant all on DBO_TC.SEQ_WORK_ELIGIBILITY_ID to APP_DP;

--Create Synonyms for APP_MP
CREATE OR REPLACE SYNONYM APP_TC.WORK_ELIGIBILITY FOR DBO_TC.WORK_ELIGIBILITY;
GRANT ALL ON DBO_TC.WORK_ELIGIBILITY TO APP_TC;

CREATE OR REPLACE SYNONYM APP_MP.WORK_ELIGIBILITY FOR DBO_TC.WORK_ELIGIBILITY;
GRANT ALL ON DBO_TC.WORK_ELIGIBILITY TO APP_MP;

CREATE OR REPLACE SYNONYM APP_DP.WORK_ELIGIBILITY FOR DBO_TC.WORK_ELIGIBILITY;
GRANT ALL ON DBO_TC.WORK_ELIGIBILITY TO APP_DP;


COMMIT;