--TAL-1335 STARTS
CREATE OR REPLACE SYNONYM APP_TC.DEALS FOR DBO_DP.DEALS;
GRANT ALL ON DBO_DP.DEALS TO APP_TC;

CREATE OR REPLACE SYNONYM APP_MP.DEALS FOR DBO_DP.DEALS;
GRANT ALL ON DBO_DP.DEALS TO APP_MP;

CREATE OR REPLACE SYNONYM APP_DP.DEALS FOR DBO_DP.DEALS;
GRANT ALL ON DBO_DP.DEALS TO APP_DP;


CREATE OR REPLACE SYNONYM APP_TC.PARTICIPANTS FOR DBO_DP.PARTICIPANTS;
GRANT ALL ON DBO_DP.PARTICIPANTS TO APP_TC;

CREATE OR REPLACE SYNONYM APP_MP.PARTICIPANTS FOR DBO_DP.PARTICIPANTS;
GRANT ALL ON DBO_DP.PARTICIPANTS TO APP_MP;

CREATE OR REPLACE SYNONYM APP_DP.PARTICIPANTS FOR DBO_DP.PARTICIPANTS;
GRANT ALL ON DBO_DP.PARTICIPANTS TO APP_DP;


CREATE OR REPLACE SYNONYM APP_TC.PROJECT_TITLE FOR DBO_MP.PROJECT_TITLE;
GRANT ALL ON DBO_MP.PROJECT_TITLE TO APP_TC;

CREATE OR REPLACE SYNONYM APP_MP.PROJECT_TITLE FOR DBO_MP.PROJECT_TITLE;
GRANT ALL ON DBO_MP.PROJECT_TITLE TO APP_MP;

CREATE OR REPLACE SYNONYM APP_DP.PROJECT_TITLE FOR DBO_MP.PROJECT_TITLE;
GRANT ALL ON DBO_MP.PROJECT_TITLE TO APP_DP;

COMMIT;

--TAL-1335 ENDS