DECLARE
   v_cnt   NUMBER := 0;
   V_QRY  VARCHAR2(4000);
   P_TABLE_NAME VARCHAR2(1000):='STATES';
   v_s_cnt   NUMBER := 0;
   v_cnt2 NUMBER := 0;
   
BEGIN
       
    SELECT COUNT (*)
    INTO v_cnt
     FROM ALL_TABLES
    WHERE TABLE_NAME = 'STATES' AND owner = 'DBO_TC';

   IF v_cnt = 0 
   THEN
       --
         EXECUTE IMMEDIATE 'create table DBO_TC.STATES ( STATE_ID NUMBER(10,0) NOT NULL, 
														STATE_NAME VARCHAR2(255 BYTE), 
														COUNTRY_CODE VARCHAR2(10 BYTE),

														CONSTRAINT PK_STATE_ID PRIMARY KEY (STATE_ID)
                                                            )';  
--  
        EXECUTE IMMEDIATE 'ALTER TABLE DBO_TC.STATES ADD CONSTRAINT FK_COUNTRY_CODE FOREIGN KEY(COUNTRY_CODE) REFERENCES DBO_TC.COUNTRIES(COUNTRY_CODE)';
		EXECUTE IMMEDIATE 'CREATE SEQUENCE DBO_TC.SEQ_STATES_ID  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE';
		
         EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM APP_TC.STATES FOR DBO_TC.STATES';
         EXECUTE IMMEDIATE 'GRANT ALL ON DBO_TC.STATES TO APP_TC';
		 
		 EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM DBO_MP.STATES FOR DBO_TC.STATES';
         EXECUTE IMMEDIATE 'GRANT ALL ON DBO_TC.STATES TO DBO_MP';
           --
         EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM APP_TC.SEQ_STATES_ID FOR DBO_TC.SEQ_STATES_ID';
         EXECUTE IMMEDIATE 'GRANT ALL ON DBO_TC.SEQ_STATES_ID TO APP_TC';
		 
		 EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM DBO_MP.SEQ_STATES_ID FOR DBO_TC.SEQ_STATES_ID';
         EXECUTE IMMEDIATE 'GRANT ALL ON DBO_TC.SEQ_STATES_ID TO DBO_MP';
		 
   END IF;
--
   COMMIT;
END;
/