alter table DBO_TC.GENDER_PLAYS drop COLUMN id;
alter table DBO_TC.RACE_PLAYS drop COLUMN id;

drop SEQUENCE dbo_tc.SEQ_GENDER_PLAYS_ID;

drop SEQUENCE dbo_tc.SEQ_RACE_PLAYS_ID;

-- Create the citizeship table
CREATE TABLE DBO_TC.PERSON_CITIZENSHIP (
  PARTY_ID NUMBER(11,0) NOT NULL ENABLE,
  CITIZENSHIP_SYS_PROP_VAL_ID NUMBER(11,0) NOT NULL ENABLE
);

ALTER TABLE DBO_TC.PERSON_CITIZENSHIP ADD CONSTRAINT FK_CITIZENSHIP_PARTY_ID FOREIGN KEY (PARTY_ID) REFERENCES DBO_TC.PARTY(PARTY_ID);
ALTER TABLE DBO_TC.PERSON_CITIZENSHIP ADD CONSTRAINT FK_CITIZENSHIP_SYS_PROP_VAL_ID FOREIGN KEY (CITIZENSHIP_SYS_PROP_VAL_ID) REFERENCES DBO_TC.SYS_PROP_VALUE(PROP_ID);


CREATE OR REPLACE SYNONYM APP_TC.PERSON_CITIZENSHIP FOR DBO_TC.PERSON_CITIZENSHIP;
GRANT ALL ON DBO_TC.PERSON_CITIZENSHIP TO APP_TC;
