
CREATE TABLE DBO_TC.PARTY_STUDIOS_ATTR
(
  ID                     NUMBER(11,0)          NOT NULL,
  PARTY_ID  			 NUMBER(11,0)          NOT NULL, 				 
  STUDIO_LOOKUP_ID       NUMBER(11,0)		   NOT NULL,
  NOTES 				 VARCHAR(3000),
  CREDITS 				 VARCHAR(3000),
  STATUS_ID              NUMBER(11,0),
  LAST_UPDATED_TS        TIMESTAMP(9) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LAST_UPDATED_USER      VARCHAR2(50 BYTE)     NOT NULL,

  CONSTRAINT PK_PARTY_STUDIOS_ATTR_ID PRIMARY KEY (ID)
);

ALTER TABLE DBO_TC.PARTY_STUDIOS_ATTR ADD CONSTRAINT FK_PARTY_STATUS_ID FOREIGN KEY(STATUS_ID) REFERENCES DBO_TC.SYS_PROP_VALUE(PROP_ID);
ALTER TABLE DBO_TC.PARTY_STUDIOS_ATTR ADD CONSTRAINT FK_PARTY_STUDIOS_ATTR_PARTY_ID FOREIGN KEY(PARTY_ID) REFERENCES DBO_TC.PARTY(PARTY_ID);

CREATE SEQUENCE DBO_TC.SEQ_PARTY_STUDIOS_ATTR_ID  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

------------- Create synonyms
CREATE OR REPLACE SYNONYM APP_TC.SEQ_PARTY_STUDIOS_ATTR_ID FOR DBO_TC.SEQ_PARTY_STUDIOS_ATTR_ID;
grant all on DBO_TC.SEQ_PARTY_STUDIOS_ATTR_ID to APP_TC;

CREATE OR REPLACE SYNONYM APP_MP.SEQ_PARTY_STUDIOS_ATTR_ID FOR DBO_TC.SEQ_PARTY_STUDIOS_ATTR_ID;
grant all on DBO_TC.SEQ_PARTY_STUDIOS_ATTR_ID to APP_MP;

CREATE OR REPLACE SYNONYM APP_DP.SEQ_PARTY_STUDIOS_ATTR_ID FOR DBO_TC.SEQ_PARTY_STUDIOS_ATTR_ID;
grant all on DBO_TC.SEQ_PARTY_STUDIOS_ATTR_ID to APP_DP;

--Create Synonyms for APP_MP
CREATE OR REPLACE SYNONYM APP_TC.PARTY_STUDIOS_ATTR FOR DBO_TC.PARTY_STUDIOS_ATTR;
GRANT ALL ON DBO_TC.PARTY_STUDIOS_ATTR TO APP_TC;

CREATE OR REPLACE SYNONYM APP_MP.PARTY_STUDIOS_ATTR FOR DBO_TC.PARTY_STUDIOS_ATTR;
GRANT ALL ON DBO_TC.PARTY_STUDIOS_ATTR TO APP_MP;

CREATE OR REPLACE SYNONYM APP_DP.PARTY_STUDIOS_ATTR FOR DBO_TC.PARTY_STUDIOS_ATTR;
GRANT ALL ON DBO_TC.PARTY_STUDIOS_ATTR TO APP_DP;

COMMIT;