update DBO_TC.PARTY_RELATION set PRIMARY_FLAG = 'N';
  
  update DBO_TC.PARTY_RELATION set PRIMARY_FLAG = 'Y' where PARTY_RELATION_ID in ( SELECT MIN(PARTY_RELATION_ID) FROM dbo_tc.party_relation GROUP BY PARENT_ID, RELATION_TYPE);
  
  commit;