INSERT INTO DBO_TC.SYS_PROPERTY (SYS_PROP_ID, SYS_PROP_NAME) values (DBO_TC.SEQ_SYS_PROP_ID.NEXTVAL, 'REP_TYPE');

INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID, SYS_PROP_ID, PROP_VALUE, ABBR, SORT_ORDER) values 
(DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, (SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME='REP_TYPE'), 'Agent', 'Agent', 1);

INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID, SYS_PROP_ID, PROP_VALUE, ABBR, SORT_ORDER) values 
(DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, (SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME='REP_TYPE'), 'Attorney', 'Attorney', 2);

INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID, SYS_PROP_ID, PROP_VALUE, ABBR, SORT_ORDER) values 
(DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, (SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME='REP_TYPE'), 'Business Rep', 'Business Rep', 3);

INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID, SYS_PROP_ID, PROP_VALUE, ABBR, SORT_ORDER) values 
(DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, (SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME='REP_TYPE'), 'Direct', 'Direct', 4);

INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID, SYS_PROP_ID, PROP_VALUE, ABBR, SORT_ORDER) values 
(DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, (SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME='REP_TYPE'), 'Guild', 'Guild', 5);

INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID, SYS_PROP_ID, PROP_VALUE, ABBR, SORT_ORDER) values 
(DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, (SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME='REP_TYPE'), 'Manager', 'Manager', 6);

INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID, SYS_PROP_ID, PROP_VALUE, ABBR, SORT_ORDER) values 
(DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, (SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME='REP_TYPE'), 'Parent/Guardian', 'Parent/Guardian', 7);

INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID, SYS_PROP_ID, PROP_VALUE, ABBR, SORT_ORDER) values 
(DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, (SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME='REP_TYPE'), 'Production Entity', 'Production Entity', 8);

INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID, SYS_PROP_ID, PROP_VALUE, ABBR, SORT_ORDER) values 
(DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, (SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME='REP_TYPE'), 'Publicist', 'Publicist', 9);

INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID, SYS_PROP_ID, PROP_VALUE, ABBR, SORT_ORDER) values 
(DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, (SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME='REP_TYPE'), 'Union', 'Union', 10);


