--===================================================================================================================================
		--CALLSHEET_PRIORITY
	TRUNCATE TABLE DBO_TC.SYS_PROP_RC;
	COMMIT;
	
	SET DEFINE OFF;
	BEGIN
        INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Blank - New','CALLSHEET_PRIORITY');
        INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Next to Call','CALLSHEET_PRIORITY');
        INSERT INTO DBO_TC.SYS_PROP_RC VALUES('High','CALLSHEET_PRIORITY');
		INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Medium','CALLSHEET_PRIORITY');
        INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Low','CALLSHEET_PRIORITY');
       	COMMIT;
	END;
	/
	
		--CALLSHEET_PRIORITY
DECLARE
		V_LOOKUP_EXISTS VARCHAR2(5);
    V_LOOKUP_TYPE_ID NUMBER;
    V_SORT_ORDER NUMBER;
    ----------------------------
      CURSOR C1 IS SELECT * FROM DBO_TC.SYS_PROP_RC
		WHERE SYS_PROPERTY='CALLSHEET_PRIORITY';
    ------------------------------
		FUNCTION LOOKUP_VALUE_FNC(P_LOOKUP_VALUE IN VARCHAR2,P_LOOKUP_NAME IN VARCHAR2)
		RETURN VARCHAR2
		AS
		V_LOOKUP_EXIST VARCHAR2(1);
		BEGIN
		SELECT 'Y'
		INTO V_LOOKUP_EXIST
		FROM DBO_MP.LOOKUP_TYPE LT,
		DBO_MP.LOOKUP LP
		WHERE 
		LT.LOOKUP_TYPE_ID=LP.LOOKUP_TYPE_ID
		AND UPPER(LP.LOOKUP_NAME)=TRIM(UPPER(P_LOOKUP_VALUE))
		AND UPPER(LT.LOOKUP_TYPE_NAME)=TRIM(UPPER(P_LOOKUP_NAME))
		AND ROWNUM=1;
		RETURN V_LOOKUP_EXIST;
		EXCEPTION
			WHEN OTHERS THEN
				V_LOOKUP_EXIST:='N';
				RETURN V_LOOKUP_EXIST;
		END LOOKUP_VALUE_FNC;
		--==============================
		PROCEDURE LOOKUP_TYPE_FNC(P_LOOKUP_TYPE_NAME IN VARCHAR2)
		AS
		V_LOOKUP_EXIST VARCHAR2(1);
    BEGIN
		BEGIN
			SELECT 'Y'
			INTO V_LOOKUP_EXIST
			FROM DBO_MP.LOOKUP_TYPE SP
			WHERE 
			SP.LOOKUP_TYPE_NAME=P_LOOKUP_TYPE_NAME
			AND ROWNUM=1;
		 --
		EXCEPTION
			WHEN OTHERS THEN
				V_LOOKUP_EXIST:='N';
		END;
		IF V_LOOKUP_EXIST='N' THEN
			INSERT INTO DBO_MP.LOOKUP_TYPE VALUES(DBO_MP.SEQ_LOOKUP_TYPE_ID.NEXTVAL,P_LOOKUP_TYPE_NAME);
			COMMIT;
		END IF;
		END LOOKUP_TYPE_FNC;
		--===============================
		PROCEDURE  LOOKUP_VALUE_INS(P_LOOKUP_NAME IN VARCHAR2,P_LOOKUP_TYPE_ID IN NUMBER,P_SORT_ORDER IN NUMBER)
		AS
		BEGIN
		INSERT INTO DBO_MP.LOOKUP (LOOKUP_ID,LOOKUP_NAME,DISPLAY_ORDER,MNEMONIC_CODE,LOOKUP_TYPE_ID,IS_ACTIVE) 
		VALUES (DBO_MP.SEQ_LOOKUP_ID.NEXTVAL,P_LOOKUP_NAME,P_SORT_ORDER,P_LOOKUP_NAME,P_LOOKUP_TYPE_ID,NULL);
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
		END LOOKUP_VALUE_INS;
		--=============================================

    BEGIN
		--
		--check whether sys property exists
		-------------------------------
		BEGIN
			LOOKUP_TYPE_FNC('CALLSHEET_PRIORITY');		
		END;		
		-----------------------------
		BEGIN
		  SELECT SP.LOOKUP_TYPE_ID,MAX(DISPLAY_ORDER)
		  INTO V_LOOKUP_TYPE_ID,V_SORT_ORDER
		  from DBO_MP.LOOKUP_TYPE SP
		, DBO_MP.LOOKUP SPN
		WHERE LOOKUP_TYPE_NAME='CALLSHEET_PRIORITY'
		AND SPN.LOOKUP_TYPE_ID=SP.LOOKUP_TYPE_ID
		GROUP BY SP.LOOKUP_TYPE_ID;
		  EXCEPTION
			WHEN OTHERS  THEN 
			  DBMS_OUTPUT.PUT_LINE('LOOKUP for does not exist CALLSHEET_PRIORITY');
			END;
			--
		IF V_LOOKUP_TYPE_ID IS NOT NULL THEN 
		--
		FOR I IN C1 
		LOOP
			BEGIN
			V_LOOKUP_EXISTS:='N';
			V_SORT_ORDER:=V_SORT_ORDER+1;
			V_LOOKUP_EXISTS:=LOOKUP_VALUE_FNC(I.SYS_PROP_VALUE,I.SYS_PROPERTY);
			IF V_LOOKUP_EXISTS='N' THEN 
				LOOKUP_VALUE_INS(I.SYS_PROP_VALUE,V_LOOKUP_TYPE_ID,V_SORT_ORDER);
			END IF;
			END;
      END LOOP;
	  COMMIT;
			--
		END IF;
	END;
	
	