DECLARE
  S_PRESENT NUMBER;
BEGIN
  BEGIN
    SELECT 1
    INTO S_PRESENT
    FROM ALL_CONSTRAINTS
    WHERE TABLE_NAME     ='CALLSHEET'
    AND OWNER            ='DBO_MP'
    AND CONSTRAINT_TYPE  ='R'
    AND R_CONSTRAINT_NAME='PK_LOOKUP_ID'
    AND CONSTRAINT_NAME LIKE '%STATUS_ID%';
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    S_PRESENT:=0;
  END;
  IF S_PRESENT=0 THEN
   EXECUTE IMMEDIATE 'ALTER TABLE DBO_MP.CALLSHEET ADD CONSTRAINT FK_CS_STATUS_ID FOREIGN KEY(STATUS_ID) REFERENCES DBO_MP.LOOKUP(LOOKUP_ID)';
  END IF;
END;
/

DECLARE
  S_PRESENT NUMBER;
BEGIN
  BEGIN
    SELECT 1
    INTO S_PRESENT
    FROM ALL_CONSTRAINTS
    WHERE TABLE_NAME     ='CALLSHEET'
    AND OWNER            ='DBO_MP'
    AND CONSTRAINT_TYPE  ='R'
    AND R_CONSTRAINT_NAME='PK_LOOKUP_ID'
    AND CONSTRAINT_NAME LIKE '%PRIORITY_ID%';
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    S_PRESENT:=0;
  END;
  IF S_PRESENT=0 THEN
   EXECUTE IMMEDIATE 'alter table DBO_MP.CALLSHEET add constraint FK_CS_PRIORITY_ID foreign key(PRIORITY_ID) references DBO_MP.LOOKUP(LOOKUP_ID)';
  END IF;
END;
/