DELETE FROM DBO_TC.SYS_PROP_VALUE where SYS_PROP_ID= (SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_CREATIVE_BUSINESS');
DELETE FROM DBO_TC.SYS_PROP_VALUE where SYS_PROP_ID =(SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_CASTING');
DELETE FROM DBO_TC.SYS_PROP_VALUE where SYS_PROP_ID =(SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_PRODUCTION');

DELETE FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_CASTING';
DELETE FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_CREATIVE_BUSINESS';
DELETE FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_PRODUCTION';

INSERT INTO DBO_MP.PERMISSIONS (PERMISSION_ID, NAME, DESCRIPTION, LAST_UPDATE_TS, LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.NEXTVAL, 'TALENT.VIEW.CASTING', 'TALENT.VIEW.CASTING', SYSDATE, 'flyway');
INSERT INTO DBO_MP.PERMISSIONS (PERMISSION_ID, NAME, DESCRIPTION, LAST_UPDATE_TS, LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.NEXTVAL, 'TALENT.VIEW.CREATIVE_BUSINESS', 'TALENT.VIEW.CREATIVE_BUSINESS', SYSDATE, 'flyway');
INSERT INTO DBO_MP.PERMISSIONS (PERMISSION_ID, NAME, DESCRIPTION, LAST_UPDATE_TS, LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.NEXTVAL, 'TALENT.VIEW.PRODUCTION', 'TALENT.VIEW.PRODUCTION', SYSDATE, 'flyway');

--Have to have the or for role name to account for different setup in WB-REG enviroment. 
INSERT INTO DBO_MP.ROLE_PERMISSIONS (ROLE_PERMISSION_ID, ROLE_ID, PERMISSION_ID, LAST_UPDATE_TS, LAST_UPDATE_USER) values (DBO_MP.SEQ_ROLE_PERMISSION_ID.NEXTVAL, 
  (SELECT ROLE_ID from DBO_MP.USER_ROLE where ROLE_NAME='Business Affairs Admin Executive' OR ROLE_NAME='BA Admin Executive'),
  (SELECT PERMISSION_ID from DBO_MP.PERMISSIONS where NAME ='TALENT.VIEW.CREATIVE_BUSINESS'),
  SYSDATE,
  'flyway');
  
commit;