
ALTER TABLE dbo_tc.party_relation
ADD UPDATED_BY varchar2(50 char);

drop table dbo_tc.party_relation_audit;

BEGIN
   DBO_TC.CREATE_AUDIT_TABLES_TIMELINE ('DBO_TC','PARTY_RELATION','PARTY_RELATION');
    Execute Immediate 'CREATE OR REPLACE SYNONYM APP_TC.PARTY_RELATION_AUDIT FOR DBO_TC.PARTY_RELATION_AUDIT';
    Execute Immediate 'grant all on DBO_TC.PARTY_RELATION_AUDIT to APP_TC';   
END;
/

--PARTY_RELATION_AUDIT_TRIGGER
CREATE OR REPLACE TRIGGER "DBO_TC"."PARTY_RELATION_AUDIT_TRIGGER" AFTER INSERT OR UPDATE OR DELETE ON dbo_tc.PARTY_RELATION
FOR EACH ROW
DECLARE
BEGIN

IF INSERTING THEN
  insert into DBO_TC.PARTY_RELATION_AUDIT (  PARENT_ID  , CHILD_ID  , RELATION_TYPE  , PARTY_RELATION_ID , RELATION_CREATED_ON , UPDATED_BY_APP  , OCCUPATION_ID  , PRIMARY_FLAG  , RELATION_NAME ,UPDATED_BY , DML_INDICATOR , DML_TIMESTAMP ) 
  values (  :new.PARENT_ID  , :new.CHILD_ID  , :new.RELATION_TYPE  , :new.PARTY_RELATION_ID , :new.RELATION_CREATED_ON  , :new.UPDATED_BY_APP  , :new.OCCUPATION_ID  , :new.PRIMARY_FLAG  , :new.RELATION_NAME ,:new.UPDATED_BY , 'I' , SYSTIMESTAMP ); 
  END IF;

IF UPDATING THEN
 insert into DBO_TC.PARTY_RELATION_AUDIT (  PARENT_ID  , CHILD_ID  , RELATION_TYPE  , PARTY_RELATION_ID , RELATION_CREATED_ON  , UPDATED_BY_APP  , OCCUPATION_ID  , PRIMARY_FLAG  , RELATION_NAME ,UPDATED_BY , DML_INDICATOR , DML_TIMESTAMP ) 
  values (  :new.PARENT_ID  , :new.CHILD_ID  , :new.RELATION_TYPE  , :new.PARTY_RELATION_ID , :new.RELATION_CREATED_ON  , :new.UPDATED_BY_APP  , :new.OCCUPATION_ID  , :new.PRIMARY_FLAG  , :new.RELATION_NAME ,:new.UPDATED_BY , 'U' , SYSTIMESTAMP );
  END IF;

IF DELETING THEN
 insert into DBO_TC.PARTY_RELATION_AUDIT (  PARENT_ID  , CHILD_ID  , RELATION_TYPE  , PARTY_RELATION_ID , RELATION_CREATED_ON  , UPDATED_BY_APP  , OCCUPATION_ID  , PRIMARY_FLAG  , RELATION_NAME ,UPDATED_BY , DML_INDICATOR , DML_TIMESTAMP ) 
  values (  :old.PARENT_ID  , :old.CHILD_ID  , :old.RELATION_TYPE  , :old.PARTY_RELATION_ID , :old.RELATION_CREATED_ON  , :old.UPDATED_BY_APP  , :old.OCCUPATION_ID  , :old.PRIMARY_FLAG  , :old.RELATION_NAME,:old.UPDATED_BY  , 'D' , SYSTIMESTAMP );
 END IF;

END;