ALTER TABLE DBO_MP.CALLSHEET RENAME COLUMN CONTACT_ID TO PARTY_ID;

ALTER TABLE DBO_MP.CALLSHEET RENAME COLUMN PHONE_ID TO WEBCONTACT_TYPE_ID;

ALTER TABLE DBO_MP.CALLSHEET RENAME COLUMN PHONE_NO TO WEBCONTACT_VALUE;