ALTER TABLE DBO_TC.SYS_PROPERTY MODIFY (SYS_PROP_NAME VARCHAR2 (30 BYTE));
ALTER TABLE DBO_TC.SYS_PROP_VALUE MODIFY (PROP_VALUE VARCHAR2 (60 BYTE));

INSERT INTO DBO_TC.SYS_PROPERTY (SYS_PROP_ID, SYS_PROP_NAME) values (DBO_TC.SEQ_SYS_PROP_ID.NEXTVAL, 'TALENT_VIEW_CASTING');
INSERT INTO DBO_TC.SYS_PROPERTY (SYS_PROP_ID, SYS_PROP_NAME) values (DBO_TC.SEQ_SYS_PROP_ID.NEXTVAL, 'TALENT_VIEW_CREATIVE_BUSINESS');
INSERT INTO DBO_TC.SYS_PROPERTY (SYS_PROP_ID, SYS_PROP_NAME) values (DBO_TC.SEQ_SYS_PROP_ID.NEXTVAL, 'TALENT_VIEW_PRODUCTION');

INSERT INTO DBO_TC.SYS_PROP_VALUE (SYS_PROP_ID, PROP_ID, PROP_VALUE) values ((SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_CREATIVE_BUSINESS'), DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, 'Senior Business Affairs Executive');
INSERT INTO DBO_TC.SYS_PROP_VALUE (SYS_PROP_ID, PROP_ID, PROP_VALUE) values ((SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_CREATIVE_BUSINESS'), DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, 'Business Affairs Admin Executive');
INSERT INTO DBO_TC.SYS_PROP_VALUE (SYS_PROP_ID, PROP_ID, PROP_VALUE) values ((SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_CREATIVE_BUSINESS'), DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, 'BA Admin Asst');

INSERT INTO DBO_TC.SYS_PROP_VALUE (SYS_PROP_ID, PROP_ID, PROP_VALUE) values ((SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_PRODUCTION'), DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, 'Prod Admin Assistant');
INSERT INTO DBO_TC.SYS_PROP_VALUE (SYS_PROP_ID, PROP_ID, PROP_VALUE) values ((SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_PRODUCTION'), DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, 'Post Prod Assistant');
INSERT INTO DBO_TC.SYS_PROP_VALUE (SYS_PROP_ID, PROP_ID, PROP_VALUE) values ((SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_PRODUCTION'), DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, 'Post Prod Admin');

INSERT INTO DBO_TC.SYS_PROP_VALUE (SYS_PROP_ID, PROP_ID, PROP_VALUE) values ((SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_CASTING'), DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, 'Senior Exec');
INSERT INTO DBO_TC.SYS_PROP_VALUE (SYS_PROP_ID, PROP_ID, PROP_VALUE) values ((SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_CASTING'), DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, 'Production Payroll');
INSERT INTO DBO_TC.SYS_PROP_VALUE (SYS_PROP_ID, PROP_ID, PROP_VALUE) values ((SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'TALENT_VIEW_CASTING'), DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL, 'Budget Manager');

COMMIT;