SET DEFINE OFF;
BEGIN
 INSERT INTO DBO_TC.SYS_PROP_RC VALUES('1st Assistant Accountant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('1st Assistant Camera','	CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('1st Assistant Camera "A"','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('1st Assistant Camera "B"','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('1st Assistant Director ','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('1st Assistant Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('2nd 2nd Assistant Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('2nd Assistant Accountant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('2nd Assistant Camera "A"','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('2nd Assistant Camera "B"','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('2nd Assistant Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('2nd Assistant Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('2nd Unit Cinematographer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('2nd Unit Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Accountant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Accounting Clerk','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Actor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Additional Music By','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Add''l 1st Asst Accountant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('ADR Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('ADR Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Animal Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Animal Performer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Animal Trainer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Animation Checker','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Animation Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Animation Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Animation Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Animator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('APOC - Asst. Prod. Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Apprentice Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Armorer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Art Department Assistant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Art Dept. Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Art Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Assistant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Assistant Art Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Assistant Costume Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Assistant Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Assistant Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Assistant Location Manager','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Assistant Payroll Accountant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Assistant Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Assistant Prop Master','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Assistant Set Decorator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Associate Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Associate Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Attorney','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Audience Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Background Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Based on a Story By','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Based on Characters By','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Best Boy','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Best Boy Electric','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Best Boy Grip','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Best Boy Rigging Grip','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Bond Company','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Boom Operator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Broadcast Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Bureau Chief','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Business Affairs','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Business Affairs Admin.','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Camera Loader','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Camera Operator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Camera Operator "A"','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Camera Operator "B"','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Camera Operator "C"','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Camera Package','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Cast','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Casting Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Caterer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Character Design','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Character Layout','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Charge Scenic','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Choreographer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Cinematographer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Clearance Status','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Co-Executive Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Completion Bond','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Composer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Construction Accountant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Construction Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Consultant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Consulting Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Contestant Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Coordinating News Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Coordinating Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Co-Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Costume Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Costume Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Costume Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Costumer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Co-Supervising Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Craftservice Key','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Created By','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Creative Consultant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Creative Executive','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Creature Design','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Creature Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Developed By','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Dgtl Intrmd Fac','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Dialogue Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Digital Effects','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Digital Effects Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Digital Effects Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Digital Effects Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Director Photography','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('DIT-Digital Imaging Technician','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Dolly Grip','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Editorial Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Editor-in-Chief','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Electric Package','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Executive Consultant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Executive Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Executive Editorial Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Executive in Charge','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Executive Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Executive Script Consultant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Executive Story Consultant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Executive Story Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Extras Casting Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Field Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Fight Choreography','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Final Mix Company','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Floor Manager','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Foley Artist','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Foley Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Foley Mixer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Gaffer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('General Foreman','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Global Partnerships','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Graphic Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Greens Foreman (Construction)','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Greensman (on set)','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Grip','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Grip Package','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Hair','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Insurance Carrier','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Investigative Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Key 2nd Asst Accountant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Key Grip','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Key Hair Stylist','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Key Makeup Artiist','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Key Rigging Grip','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Labor Relations','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Leadman Set Dressing','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Legal','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Lighting Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Lighting Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Line Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Lip Sync','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Location Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Location Manager','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Main Titles Designed By','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Makeup','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Makeup Effects','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Managing Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Marketing','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Mexico Co-Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Miniatures','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Mo.Cap. Line Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('MP Post. Finance','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('MP Prod. Finance','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Music Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Music Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Music Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Music Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Music/Record Company','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Musical Group','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('News Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('News Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('On Set Dresser','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('On-Line Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Operations Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Operations Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Orchestrations','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Original Casting','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Original Songs by','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Paint Foreman','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Partner','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Payroll Acccountant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Payroll Company','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Picture Car Captain','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Plaster Foreman','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Post Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Post Production Accnt','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Post Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Post-Production','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Post-Production Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Post-Production Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Post-Production Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Producing Company','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Accountant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Associate','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Consultant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Controller','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Manager','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Mgr - Berlin','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Mgr - Canada','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Mgr - France','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Mgr - UK','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Prop Design','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Prop Master','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Property Master','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Propmaker Foreman','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Publicity Contact','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Release Prt Lab','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Re-Recording Mixer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Researcher','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Rigging Electric Best Boy','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Rigging Gaffer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Rights & Clearances','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Role','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Scoring','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Scoring Mixer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Screenplay','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Script Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Script Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Segment Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Segment Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Senior Broadcast Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Senior Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Senior Editorial Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Senior Field Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Senior Investigative Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Senior News Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Senior News Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Senior Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Senior Segment Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Senior Set Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Series Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Set Costumer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Set Dec Buyer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Set Decorator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Set Design','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Set Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Set Standby Painter','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sound','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sound Boom Operator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sound Cableperson','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sound Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sound Effects','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sound Effects (Vendors)','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sound Effects Mixer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sound Mixer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sound Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Special Effects','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Special Effects Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Special Effects Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Special Effects Foreman','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Special Effects Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Special Effects Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Special Projects Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('SPR Sound FX Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Sr. Special Projects Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Staff Accountant Assigned to Film','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Staff Writer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Stage Manager','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Star Hair','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Star Make-up','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Star Wardrobe','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Steadicam Assistant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Steadicam Operator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Stills Photography','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Story','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Story & Teleplay','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Story Consultant','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Story Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Storyboard Artist','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Stunt Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Stunt Performer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Supervising Art Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Supervising Associate Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Supervising Dialogue Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Supervising Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Supervising Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Supervising Executive Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Supervising Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Supervising Sound Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Talent','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Talent Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Talent Executive','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Technical Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Theme By','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Timing Director','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Title Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Transportation Captain','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Transportation Co-Captain','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Transportation Coordinator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Unit Manager','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Unit Production Manager','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Unit Publicist','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('VFX DP','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('VFX Editor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('VFX Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('VFX Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('VFX Vendor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Video Assist Operator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Video Playback Operator','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Visual Effects','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Visual Effects Designer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Visual Effects Producer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Visual Effects Supervisor','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Voice Casting','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Voice Directing','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Wardrobe','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Wardrobe Provided By','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Welder Foreman','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Writer','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Parent/Guardian','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Production Entity','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Direct','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Publicist','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Crew','CONTACT_OCCUPATION');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Performer','CONTACT_OCCUPATION');
COMMIT;
	END;
	/
---CONTACT_OCCUPATION

DECLARE
		V_SYS_PROP_EXIST VARCHAR2(5);
    V_SYS_PROP_ID NUMBER;
    V_SORT_ORDER NUMBER := 1;
    ----------------------------
      CURSOR C1 IS SELECT * FROM DBO_TC.SYS_PROP_RC
		WHERE SYS_PROPERTY='CONTACT_OCCUPATION';
		
		CURSOR C2 IS 
		SELECT * FROM 
			DBO_TC.SYS_PROP_VALUE 
		WHERE 
			SYS_PROP_ID=(SELECT SYS_PROP_ID FROM DBO_TC.SYS_PROPERTY WHERE SYS_PROP_NAME='CONTACT_OCCUPATION')
		ORDER BY PROP_VALUE ASC;
    ------------------------------
		FUNCTION SYS_PROP_VALUE_FNC(P_SYS_PROP_VALUE IN VARCHAR2,P_SYS_PROP_NAME IN VARCHAR2)
    RETURN VARCHAR2
		AS
		V_SYS_PROP_EXIST VARCHAR2(1);
		BEGIN
		SELECT 'Y'
		INTO V_SYS_PROP_EXIST
		FROM DBO_TC.SYS_PROPERTY SP,
		DBO_TC.SYS_PROP_VALUE SPV
		WHERE 
		SP.SYS_PROP_ID=SPV.SYS_PROP_ID
		AND UPPER(SPV.PROP_VALUE)=TRIM(UPPER(P_SYS_PROP_VALUE))
		AND UPPER(SP.SYS_PROP_NAME)=TRIM(UPPER(P_SYS_PROP_NAME));
		RETURN V_SYS_PROP_EXIST;
		EXCEPTION
			WHEN OTHERS THEN
				V_SYS_PROP_EXIST:='N';
				RETURN V_SYS_PROP_EXIST;
		END SYS_PROP_VALUE_FNC;
		--===============================
		PROCEDURE  SYS_PROP_VALUE_INS(P_SYS_PROP_VALUE IN VARCHAR2,P_SYS_PROP_ID IN NUMBER)
		AS
		BEGIN
		INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) 
		VALUES (DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL,P_SYS_PROP_ID,P_SYS_PROP_VALUE,P_SYS_PROP_VALUE,null);
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
		END SYS_PROP_VALUE_INS;
		--=============================================

    BEGIN
		--
		BEGIN
		  SELECT SP.SYS_PROP_ID
		  INTO V_SYS_PROP_ID
		  from DBO_TC.SYS_PROPERTY SP
		, DBO_TC.SYS_PROP_VALUE SPN
		WHERE SYS_PROP_NAME='CONTACT_OCCUPATION'
		AND SPN.SYS_PROP_ID=SP.SYS_PROP_ID
		GROUP BY SP.SYS_PROP_ID;
		  EXCEPTION
			WHEN OTHERS  THEN 
			  DBMS_OUTPUT.PUT_LINE('V_SYS_PROP_ID for does not exist CONTACT_OCCUPATION');
			END;
			--
		IF V_SYS_PROP_ID IS NOT NULL THEN 
		--
		FOR I IN C1 
		LOOP
			BEGIN
			V_SYS_PROP_EXIST:='N';
			V_SYS_PROP_EXIST:=SYS_PROP_VALUE_FNC(I.SYS_PROP_VALUE,I.SYS_PROPERTY);
			IF V_SYS_PROP_EXIST='N' THEN 
				SYS_PROP_VALUE_INS(I.SYS_PROP_VALUE,V_SYS_PROP_ID);
			END IF;
			END;
		END LOOP;
		COMMIT;
		
		FOR J IN C2
		LOOP
		BEGIN
			DBMS_OUTPUT.PUT_LINE  ('UPDATING PROP_ID: ' || J.PROP_ID || ' SORT ORDER AS ' || V_SORT_ORDER);
			UPDATE DBO_TC.SYS_PROP_VALUE SET SORT_ORDER = V_SORT_ORDER WHERE PROP_ID = J.PROP_ID;
			V_SORT_ORDER := V_SORT_ORDER + 1;
		END;
		END LOOP;
		COMMIT;
			--
		END IF;
	END;
	/
	