DECLARE
   v_cnt   NUMBER := 0;
   V_QRY  VARCHAR2(4000);
   P_TABLE_NAME VARCHAR2(1000):='TALENT_AKAS';
BEGIN
   SELECT COUNT (*)
     INTO v_cnt
     FROM all_tables
    WHERE TABLE_NAME = 'TALENT_AKAS' AND owner = 'DBO_TC';

   IF v_cnt != 0
   THEN
       
      EXECUTE IMMEDIATE 'ALTER TABLE DBO_TC.TALENT_AKAS ADD FIRST_NAME VARCHAR2(100)';
       --
       EXECUTE IMMEDIATE 'ALTER TABLE DBO_TC.TALENT_AKAS ADD LAST_NAME VARCHAR2(300)';   
    
         
   END IF;
END;
