DECLARE
V_LOOKUP_TYPE number;
V_DISPLAY_ORDER VARCHAR2(100);
BEGIN
  INSERT INTO SYS_PROPERTY (SYS_PROP_ID, SYS_PROP_NAME) VALUES ( DBO_TC.SEQ_SYS_PROP_ID.NEXTVAL,'CONTACT_ENTITY_TYPE');
--
COMMIT;
  END;
/

DECLARE
V_SYS_PROP_ID number;
V_SORT_ORDER VARCHAR2(100);
BEGIN
BEGIN
  SELECT SP.SYS_PROP_ID
  INTO V_SYS_PROP_ID
  from DBO_TC.SYS_PROPERTY SP
WHERE SYS_PROP_NAME='CONTACT_ENTITY_TYPE';
  EXCEPTION
    WHEN OTHERS  THEN 
      DBMS_OUTPUT.PUT_LINE('V_SYS_PROP_ID for does not exist CONTACT_ENTITY_TYPE');
	  --	NBCU_ERROR_INSERT('Y',107,'Error in getting SYS PROP ID in STAFF_LEVEL lookup valuess','CONTACT_TYPE',NULL,NULL,NULL,NULL,NULL);
END;
BEGIN
  SELECT MAX(SORT_ORDER)
  INTO V_SORT_ORDER
  FROM DBO_TC.SYS_PROP_VALUE SPN;
  EXCEPTION
    WHEN OTHERS  THEN 
	
      DBMS_OUTPUT.PUT_LINE('V_SORT_ORDER for does not exist CONTACT_ENTITY_TYPE');
	  --	NBCU_ERROR_INSERT('Y',107,'Error in getting SYS PROP ID in STAFF_LEVEL lookup valu
END;
--
IF V_SYS_PROP_ID IS NOT NULL THEN 
begin
	V_SORT_ORDER:=V_SORT_ORDER+1; 
	INSERT INTO SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) VALUES (DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL,V_SYS_PROP_ID,'Business','Business',V_SORT_ORDER);
	V_SORT_ORDER:=V_SORT_ORDER+1; 
	INSERT INTO SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) VALUES (DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL,V_SYS_PROP_ID,'Personal','Personal',V_SORT_ORDER);
	COMMIT;
	EXCEPTION
		WHEN OTHERS  THEN 
			DBMS_OUTPUT.PUT_LINE('Error in inserting data to CONTACT_ENTITY_TYPE sys prop values');
	 ROLLBACK;
END;      
      
--END;
END IF;
END;
/