
CREATE TABLE DBO_TC.GENRE 
( PARTY_ID NUMBER NOT NULL 
, GENRE_NAME_ID NUMBER NOT NULL 
) ;

CREATE OR REPLACE SYNONYM APP_TC.GENRE FOR DBO_TC.GENRE;
grant all on DBO_TC.GENRE to APP_TC;

CREATE OR REPLACE SYNONYM APP_MP.GENRE FOR DBO_TC.GENRE;
grant all on DBO_TC.GENRE to APP_MP;

CREATE OR REPLACE SYNONYM APP_DP.GENRE FOR DBO_TC.GENRE;
grant all on DBO_TC.GENRE to APP_DP;

