ALTER TABLE DBO_MP.CALLSHEET MODIFY (CREATED_BY VARCHAR2(50), UPDATED_BY VARCHAR2(50));
ALTER TABLE DBO_TC.PARTY MODIFY (CREATED_BY VARCHAR2(50), UPDATED_BY VARCHAR2(50));
Alter Table Dbo_Tc.Party_Contact Modify (Created_By	 Varchar2(50), Updated_By Varchar2(50));
COMMIT;