--ADDRESS_TYPE
TRUNCATE TABLE DBO_TC.SYS_PROP_RC;
COMMIT;


	BEGIN
		INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Primary','ADDRESS_TYPE');
		INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Alternate Home','ADDRESS_TYPE');
		INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Vacation','ADDRESS_TYPE');
		INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Work','ADDRESS_TYPE');
		INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Mailing','ADDRESS_TYPE');
		COMMIT;
	END;
	/
	
	
	--ADDRESS_TYPE
DECLARE
		V_SYS_PROP_EXIST VARCHAR2(5);
    V_SYS_PROP_ID NUMBER;
    V_SORT_ORDER NUMBER;
    ----------------------------
      CURSOR C1 IS SELECT * FROM DBO_TC.SYS_PROP_RC
		WHERE SYS_PROPERTY='ADDRESS_TYPE';
    ------------------------------
		FUNCTION SYS_PROP_VALUE_FNC(P_SYS_PROP_VALUE IN VARCHAR2,P_SYS_PROP_NAME IN VARCHAR2)
    RETURN VARCHAR2
		AS
		V_SYS_PROP_EXIST VARCHAR2(1);
		BEGIN
		SELECT 'Y'
		INTO V_SYS_PROP_EXIST
		FROM DBO_TC.SYS_PROPERTY SP,
		DBO_TC.SYS_PROP_VALUE SPV
		WHERE 
		SP.SYS_PROP_ID=SPV.SYS_PROP_ID
		AND UPPER(SPV.PROP_VALUE)=TRIM(UPPER(P_SYS_PROP_VALUE))
		AND UPPER(SP.SYS_PROP_NAME)=TRIM(UPPER(P_SYS_PROP_NAME));
		RETURN V_SYS_PROP_EXIST;
		EXCEPTION
			WHEN OTHERS THEN
				V_SYS_PROP_EXIST:='N';
				RETURN V_SYS_PROP_EXIST;
		END SYS_PROP_VALUE_FNC;
		--===============================
		PROCEDURE  SYS_PROP_VALUE_INS(P_SYS_PROP_VALUE IN VARCHAR2,P_SYS_PROP_ID IN NUMBER,P_SORT_ORDER IN NUMBER)
		AS
		BEGIN
		INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) 
		VALUES (DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL,P_SYS_PROP_ID,P_SYS_PROP_VALUE,P_SYS_PROP_VALUE,P_SORT_ORDER);
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
		END SYS_PROP_VALUE_INS;
		--=============================================

    BEGIN
		--
		BEGIN
		  SELECT SP.SYS_PROP_ID,MAX(SORT_ORDER)
		  INTO V_SYS_PROP_ID,V_SORT_ORDER
		  from DBO_TC.SYS_PROPERTY SP
		, DBO_TC.SYS_PROP_VALUE SPN
		WHERE SYS_PROP_NAME='ADDRESS_TYPE'
		AND SPN.SYS_PROP_ID=SP.SYS_PROP_ID
		GROUP BY SP.SYS_PROP_ID;
		  EXCEPTION
			WHEN OTHERS  THEN 
			  DBMS_OUTPUT.PUT_LINE('V_SYS_PROP_ID for does not exist ADDRESS_TYPE');
			END;
			--
		IF V_SYS_PROP_ID IS NOT NULL THEN 
		--
		FOR I IN C1 
		LOOP
			BEGIN
			V_SYS_PROP_EXIST:='N';
			V_SORT_ORDER:=V_SORT_ORDER+1;
			V_SYS_PROP_EXIST:=SYS_PROP_VALUE_FNC(I.SYS_PROP_VALUE,I.SYS_PROPERTY);
			IF V_SYS_PROP_EXIST='N' THEN 
				SYS_PROP_VALUE_INS(I.SYS_PROP_VALUE,V_SYS_PROP_ID,V_SORT_ORDER);
			END IF;
			END;
      END LOOP;
	  COMMIT;
			--
		END IF;
	END;
	
	