--Representative Details tabs
Insert into DBO_MP.PERMISSIONS (PERMISSION_ID,NAME,DESCRIPTION,LAST_UPDATE_TS,LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.nextval,'Talent.RepDetails.Submission.VIEW','Talent.RepDetails.Submission.VIEW',SYSTIMESTAMP,'flyway');      
Insert into DBO_MP.PERMISSIONS (PERMISSION_ID,NAME,DESCRIPTION,LAST_UPDATE_TS,LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.nextval,'Talent.RepDetails.Submission.UPDATE','Talent.RepDetails.Submission.UPDATE',SYSTIMESTAMP,'flyway');
Insert into DBO_MP.PERMISSIONS (PERMISSION_ID,NAME,DESCRIPTION,LAST_UPDATE_TS,LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.nextval,'Talent.RepDetails.Submission.CREATE','Talent.RepDetails.Submission.CREATE',SYSTIMESTAMP,'flyway');
Insert into DBO_MP.PERMISSIONS (PERMISSION_ID,NAME,DESCRIPTION,LAST_UPDATE_TS,LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.nextval,'Talent.RepDetails.Submission.DELETE','Talent.RepDetails.Submission.DELETE',SYSTIMESTAMP,'flyway');

Insert into DBO_MP.PERMISSIONS (PERMISSION_ID,NAME,DESCRIPTION,LAST_UPDATE_TS,LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.nextval,'Talent.RepDetails.Deals.VIEW','Talent.RepDetails.Deals.VIEW',SYSTIMESTAMP,'flyway');      
Insert into DBO_MP.PERMISSIONS (PERMISSION_ID,NAME,DESCRIPTION,LAST_UPDATE_TS,LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.nextval,'Talent.RepDetails.Deals.UPDATE','Talent.RepDetails.Deals.UPDATE',SYSTIMESTAMP,'flyway');
Insert into DBO_MP.PERMISSIONS (PERMISSION_ID,NAME,DESCRIPTION,LAST_UPDATE_TS,LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.nextval,'Talent.RepDetails.Deals.CREATE','Talent.RepDetails.Deals.CREATE',SYSTIMESTAMP,'flyway');
Insert into DBO_MP.PERMISSIONS (PERMISSION_ID,NAME,DESCRIPTION,LAST_UPDATE_TS,LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.nextval,'Talent.RepDetails.Deals.DELETE','Talent.RepDetails.Deals.DELETE',SYSTIMESTAMP,'flyway');

Insert into DBO_MP.PERMISSIONS (PERMISSION_ID,NAME,DESCRIPTION,LAST_UPDATE_TS,LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.nextval,'Talent.RepDetails.Casting.VIEW','Talent.RepDetails.Casting.VIEW',SYSTIMESTAMP,'flyway');      
Insert into DBO_MP.PERMISSIONS (PERMISSION_ID,NAME,DESCRIPTION,LAST_UPDATE_TS,LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.nextval,'Talent.RepDetails.Casting.UPDATE','Talent.RepDetails.Casting.UPDATE',SYSTIMESTAMP,'flyway');
Insert into DBO_MP.PERMISSIONS (PERMISSION_ID,NAME,DESCRIPTION,LAST_UPDATE_TS,LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.nextval,'Talent.RepDetails.Casting.CREATE','Talent.RepDetails.Casting.CREATE',SYSTIMESTAMP,'flyway');
Insert into DBO_MP.PERMISSIONS (PERMISSION_ID,NAME,DESCRIPTION,LAST_UPDATE_TS,LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.nextval,'Talent.RepDetails.Casting.DELETE','Talent.RepDetails.Casting.DELETE',SYSTIMESTAMP,'flyway');

