-- Insert in SYS_PROPERTY with IMMIGRATION_STATUS
Insert into DBO_TC.SYS_PROPERTY (SYS_PROP_ID,SYS_PROP_NAME) values (SEQ_SYS_PROP_ID.NEXTVAL,'IMMIGRATION_STATUS');



-- Insert in SYS_PROP_VALUE with IMMIGRATION_STATUS and their Values
Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'IMMIGRATION_STATUS'),'0-1 Visa','0-1 Visa',1);

Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'IMMIGRATION_STATUS'),'Green Card','Green Card',2);

Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'IMMIGRATION_STATUS'),'Permanent Resident','Permanent Resident',3);

Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'IMMIGRATION_STATUS'),'0-2 Visa','0-2 Visa',4);

Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'IMMIGRATION_STATUS'),'Naturalized','Naturalized',5);

Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'IMMIGRATION_STATUS'),'Emp Auth Card','Emp Auth Card',6);

Insert into DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) values (SEQ_SYS_PROP_VALUE_ID.NEXTVAL,
(Select SYS_PROP_ID from DBO_TC.SYS_PROPERTY where SYS_PROP_NAME = 'IMMIGRATION_STATUS'),'TN1 Visa','TN1 Visa',7);


--COMMIT
COMMIT;
