grant SELECT on DBO_MP.USER_ROLE to APP_TC ;
grant SELECT on DBO_MP.PERMISSIONS to APP_TC ;
grant SELECT on DBO_MP.ROLE_PERMISSIONS to APP_TC ;

CREATE OR REPLACE SYNONYM APP_TC.USERS FOR DBO_MP.USERS;
CREATE OR REPLACE SYNONYM APP_TC.USER_ROLE FOR DBO_MP.USER_ROLE;
CREATE OR REPLACE SYNONYM APP_TC.ROLE_PERMISSIONS FOR DBO_MP.ROLE_PERMISSIONS;
CREATE OR REPLACE SYNONYM APP_TC.PERMISSIONS FOR DBO_MP.PERMISSIONS;

INSERT INTO DBO_MP.PERMISSIONS (PERMISSION_ID, NAME, DESCRIPTION, LAST_UPDATE_TS, LAST_UPDATE_USER) values (DBO_MP.SEQ_PERMISSION_ID.NEXTVAL, 'TALENT.VIEW', 'TALENT.VIEW', SYSDATE, 'flyway');

--Have to have the or for role name to account for different setup in WB-REG enviroment. 
INSERT INTO DBO_MP.ROLE_PERMISSIONS (ROLE_PERMISSION_ID, ROLE_ID, PERMISSION_ID, LAST_UPDATE_TS, LAST_UPDATE_USER) values (DBO_MP.SEQ_ROLE_PERMISSION_ID.NEXTVAL, 
  (SELECT ROLE_ID from DBO_MP.USER_ROLE where ROLE_NAME='Business Affairs Admin Executive' OR ROLE_NAME='BA Admin Executive'),
  (SELECT PERMISSION_ID from DBO_MP.PERMISSIONS where NAME ='TALENT.VIEW'),
  SYSDATE,
  'flyway');
  
COMMIT;