ALTER TABLE DBO_TC.ADDRESS ADD STATE_ID NUMBER(10,0) NULL;
DECLARE
BEGIN
	
	EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM APP_TC.ADDRESS FOR DBO_TC.ADDRESS';
	EXECUTE IMMEDIATE 'GRANT ALL ON DBO_TC.ADDRESS TO APP_TC';

	EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM DBO_MP.ADDRESS FOR DBO_TC.ADDRESS';
	EXECUTE IMMEDIATE 'GRANT ALL ON DBO_TC.ADDRESS TO DBO_MP';
	
	COMMIT;
END;
