create or replace TRIGGER "DBO_TC"."PARTY_AKA_AUDIT_TRIGGER" AFTER INSERT OR UPDATE OR DELETE ON dbo_tc.PARTY_AKA
FOR EACH ROW
DECLARE
BEGIN

IF INSERTING THEN
  insert into DBO_TC.PARTY_AKA_AUDIT (  ID , PARTY_ID , AKA_NAME  , LAST_UPDATED_USER , LAST_UPDATED_TS  , IS_CURRENT  , FIRST_NAME  , LAST_NAME  , AKA_IND  , DML_INDICATOR  , DML_TIMESTAMP  ) 
  values (  :new.ID , :new.PARTY_ID , :new.AKA_NAME  , :new.LAST_UPDATED_USER , :new.LAST_UPDATED_TS  , :new.IS_CURRENT  , :new.FIRST_NAME  , :new.LAST_NAME  , :new.AKA_IND  , 'I'  , SYSTIMESTAMP  ) ;
  END IF;

IF UPDATING THEN
 insert into DBO_TC.PARTY_AKA_AUDIT (  ID , PARTY_ID , AKA_NAME  , LAST_UPDATED_USER , LAST_UPDATED_TS  , IS_CURRENT  , FIRST_NAME  , LAST_NAME  , AKA_IND  , DML_INDICATOR  , DML_TIMESTAMP  ) 
  values (  :new.ID , :new.PARTY_ID , :new.AKA_NAME  , :new.LAST_UPDATED_USER , :new.LAST_UPDATED_TS  , :new.IS_CURRENT  , :new.FIRST_NAME  , :new.LAST_NAME  , :new.AKA_IND  , 'U'  , SYSTIMESTAMP  ) ;
  END IF;

IF DELETING THEN
 insert into DBO_TC.PARTY_AKA_AUDIT (  ID , PARTY_ID , AKA_NAME  , LAST_UPDATED_USER , LAST_UPDATED_TS  , IS_CURRENT  , FIRST_NAME  , LAST_NAME  , AKA_IND  , DML_INDICATOR  , DML_TIMESTAMP  ) 
  values (  :old.ID , :old.PARTY_ID , :old.AKA_NAME  , :old.LAST_UPDATED_USER , :old.LAST_UPDATED_TS  , :old.IS_CURRENT  , :old.FIRST_NAME  , :old.LAST_NAME  , :old.AKA_IND  , 'D'  , SYSTIMESTAMP  ) ;
 END IF;

END;
