	--PHONE_TYPE
TRUNCATE TABLE DBO_TC.SYS_PROP_RC;
COMMIT;


BEGIN
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Facebook','SOCIAL_MEDIA');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Google+','SOCIAL_MEDIA');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Instagram','SOCIAL_MEDIA');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('SnapChat','SOCIAL_MEDIA');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Tumblr','SOCIAL_MEDIA');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Twitter','SOCIAL_MEDIA');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Website','SOCIAL_MEDIA');
INSERT INTO DBO_TC.SYS_PROP_RC VALUES('Email','SOCIAL_MEDIA');
COMMIT;
END;
/
--CONTACT_TYPE
DECLARE
		V_SYS_PROP_EXIST VARCHAR2(5);
    V_SYS_PROP_ID NUMBER;
    V_SORT_ORDER NUMBER;
    ----------------------------
      CURSOR C1 IS SELECT * FROM DBO_TC.SYS_PROP_RC
		WHERE SYS_PROPERTY='SOCIAL_MEDIA';
    ------------------------------
		FUNCTION SYS_PROP_VALUE_FNC(P_SYS_PROP_VALUE IN VARCHAR2,P_SYS_PROP_NAME IN VARCHAR2)
    RETURN VARCHAR2
		AS
		V_SYS_PROP_EXIST VARCHAR2(1);
		BEGIN
		SELECT 'Y'
		INTO V_SYS_PROP_EXIST
		FROM DBO_TC.SYS_PROPERTY SP,
		DBO_TC.SYS_PROP_VALUE SPV
		WHERE 
		SP.SYS_PROP_ID=SPV.SYS_PROP_ID
		AND UPPER(SPV.PROP_VALUE)=TRIM(UPPER(P_SYS_PROP_VALUE))
		AND UPPER(SP.SYS_PROP_NAME)=TRIM(UPPER(P_SYS_PROP_NAME));
		RETURN V_SYS_PROP_EXIST;
		EXCEPTION
			WHEN OTHERS THEN
				V_SYS_PROP_EXIST:='N';
				RETURN V_SYS_PROP_EXIST;
		END SYS_PROP_VALUE_FNC;
		--===============================
		PROCEDURE  SYS_PROP_VALUE_INS(P_SYS_PROP_VALUE IN VARCHAR2,P_SYS_PROP_ID IN NUMBER,P_SORT_ORDER IN NUMBER)
		AS
		BEGIN
		INSERT INTO DBO_TC.SYS_PROP_VALUE (PROP_ID,SYS_PROP_ID,PROP_VALUE,ABBR,SORT_ORDER) 
		VALUES (DBO_TC.SEQ_SYS_PROP_VALUE_ID.NEXTVAL,P_SYS_PROP_ID,P_SYS_PROP_VALUE,P_SYS_PROP_VALUE,P_SORT_ORDER);
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
		END SYS_PROP_VALUE_INS;
		--=============================================
		PROCEDURE SYS_PROP_FNC(P_SYS_PROP_NAME IN VARCHAR2)
		AS
		V_SYS_PROP_EXIST VARCHAR2(1);
    BEGIN
		BEGIN
			SELECT 'Y'
			INTO V_SYS_PROP_EXIST
			FROM DBO_TC.SYS_PROPERTY SP
			WHERE 
			SP.SYS_PROP_NAME=P_SYS_PROP_NAME
			AND ROWNUM=1;
		 --
		EXCEPTION
			WHEN OTHERS THEN
				V_SYS_PROP_EXIST:='N';
		END;
		IF V_SYS_PROP_EXIST='N' THEN
			INSERT INTO DBO_TC.SYS_PROPERTY(SYS_PROP_ID,SYS_PROP_NAME) VALUES (DBO_TC.SEQ_SYS_PROP_ID.NEXTVAL,P_SYS_PROP_NAME);
			COMMIT;
		END IF;
		END SYS_PROP_FNC;
		--=============================================================

    BEGIN
	--check whether sys property exists
		-------------------------------
		BEGIN
			SYS_PROP_FNC('SOCIAL_MEDIA');		
		END;		
		-----------------------------
		--
		BEGIN
		SELECT SYS_PROP_ID
		  INTO V_SYS_PROP_ID
		  from DBO_TC.SYS_PROPERTY
		WHERE SYS_PROP_NAME='SOCIAL_MEDIA'
		AND ROWNUM=1;
		 EXCEPTION
			WHEN OTHERS  THEN 
			  DBMS_OUTPUT.PUT_LINE('LOOKUP for does not exist SOCIAL_MEDIA');
			END;
			BEGIN
			SELECT MAX(SORT_ORDER)
			INTO V_SORT_ORDER
			from DBO_TC.SYS_PROP_VALUE
			WHERE SYS_PROP_ID=V_SYS_PROP_ID
			AND ROWNUM=1;
		 EXCEPTION
			WHEN OTHERS  THEN 
			  DBMS_OUTPUT.PUT_LINE('sort order issue in lookup');
			END;
			--
		IF V_SYS_PROP_ID IS NOT NULL THEN 
		--
		FOR I IN C1 
		LOOP
			BEGIN
			V_SYS_PROP_EXIST:='N';
			V_SORT_ORDER:=V_SORT_ORDER+1;
			V_SYS_PROP_EXIST:=SYS_PROP_VALUE_FNC(I.SYS_PROP_VALUE,I.SYS_PROPERTY);
			IF V_SYS_PROP_EXIST='N' THEN 
				SYS_PROP_VALUE_INS(I.SYS_PROP_VALUE,V_SYS_PROP_ID,V_SORT_ORDER);
			END IF;
			END;
      END LOOP;
	  COMMIT;
			--
		END IF;
	END;
	
	
	