CREATE TABLE DBO_TC.PARTY_AKAS
(
  ID					 NUMBER(11,0)          NOT NULL,
  PARTY_ID				 NUMBER(11,0)          NOT NULL,
  AKA_NAME          	 VARCHAR2(500 BYTE)    NOT NULL,
  LAST_UPDATED_USER		 VARCHAR2(50 BYTE)     NOT NULL,
  LAST_UPDATED_TS		 TIMESTAMP(9) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  IS_CURRENTUSER 		 CHAR(1 BYTE) DEFAULT 'Y' NOT NULL,

  CONSTRAINT PK_PARTY_AKAS PRIMARY KEY (ID)

);

ALTER TABLE DBO_TC.PARTY_AKAS ADD CONSTRAINT FK_PARTY_AKA_ID FOREIGN KEY(PARTY_ID) REFERENCES DBO_TC.PARTY(PARTY_ID);

--Sequence for ID
CREATE SEQUENCE DBO_TC.SEQ_PARTY_AKAS_ID  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

------------- Create synonyms
CREATE OR REPLACE SYNONYM APP_TC.SEQ_PARTY_AKAS_ID FOR DBO_TC.SEQ_PARTY_AKAS_ID;
grant all on DBO_TC.SEQ_PARTY_AKAS_ID to APP_TC;

CREATE OR REPLACE SYNONYM APP_MP.SEQ_PARTY_AKAS_ID FOR DBO_TC.SEQ_PARTY_AKAS_ID;
grant all on DBO_TC.SEQ_PARTY_AKAS_ID to APP_MP;

CREATE OR REPLACE SYNONYM APP_DP.SEQ_PARTY_AKAS_ID FOR DBO_TC.SEQ_PARTY_AKAS_ID;
grant all on DBO_TC.SEQ_PARTY_AKAS_ID to APP_DP;

--Create Synonyms for APP_MP
CREATE OR REPLACE SYNONYM APP_TC.PARTY_AKAS FOR DBO_TC.PARTY_AKAS;
GRANT ALL ON DBO_TC.PARTY_AKAS TO APP_TC;

CREATE OR REPLACE SYNONYM APP_MP.PARTY_AKAS FOR DBO_TC.PARTY_AKAS;
GRANT ALL ON DBO_TC.PARTY_AKAS TO APP_MP;

CREATE OR REPLACE SYNONYM APP_DP.PARTY_AKAS FOR DBO_TC.PARTY_AKAS;
GRANT ALL ON DBO_TC.PARTY_AKAS TO APP_DP;


COMMIT;